# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 18.04'
variables:
- group: krypto
steps:
- task: DownloadSecureFile@1
  name: keystore
  displayName: 'Download Signing Keystore'
  inputs:
    secureFile: 'keystore'
- script: |
    echo Installing $(keystore.secureFilePath) to the keystore...;
    sudo chown root:root $(keystore.secureFilePath);
    sudo chmod a+r $(keystore.secureFilePath);
    sudo mkdir $(gpg-dir)
    sudo ln -s $(keystore.secureFilePath) $(gpg-keyring);
    sudo chmod a+r $(gpg-keyring);
    echo Listing $(gpg-dir) content...
    sudo ls -ah $(gpg-dir);
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo Secret vars...
      echo gpg.homedir=$(gpg-dir)
      echo gpg.keyname=$(gpg-keyname)
      echo gpg.keyring=$(gpg-keyring) 
      echo gpg.passphrase=$(gpg-passphrase)
      echo sonatype-oss-password=$(sonatype-oss-password)
      echo sonatype-oss-username=$(sonatype-oss-username)
- task: Maven@3
  inputs:
    mavenPomFile: 'extendedValidation-spring-boot-parent/pom.xml'
    mavenOptions: '-Xmx1024m -DskipTests -Dmaven.javadoc.skip=true 
                   -Dgpg.defaultKeyring=false
                   -Dgpg.homedir=$(gpg-dir) 
                   -Dgpg.keyname=$(gpg-keyname)
                   -Dgpg.secretKeyring=$(gpg-keyring)
                   -Dgpg.publicKeyring=$(gpg-keyring) 
                   -Dgpg.passphrase=$(gpg-passphrase)
                   -Dsonatype-oss-password=$(sonatype-oss-password)
                   -Dsonatype-oss-username=$(sonatype-oss-username)'
    goals: 'clean install'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m -Dmaven.javadoc.skip=true -s maven/settings.xml 
                   -Dgpg.defaultKeyring=false
                   -Dgpg.homedir=$(gpg-dir) 
                   -Dgpg.keyname=$(gpg-keyname)
                   -Dgpg.secretKeyring=$(gpg-keyring)
                   -Dgpg.publicKeyring=$(gpg-keyring) 
                   -Dgpg.passphrase=$(gpg-passphrase)
                   -Dsonatype-oss-password=$(sonatype-oss-password)
                   -Dsonatype-oss-username=$(sonatype-oss-username)'
    publishJUnitResults: 'true'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package verify sonar:sonar deploy'
