# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 18.04'
variables:
- group: krypto
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo Criando gpg home...
      sudo mkdir /gpg
      sudo chmod a+rw /gpg
- task: DownloadSecureFile@1
  name: public
  displayName: 'Download Signing Public Key'
  inputs:
    secureFile: 'public.asc'
- script: |
    echo Installing $(public.secureFilePath) to the keystore...
    sudo chown root:root $(public.secureFilePath)
    sudo gpg --homedir /gpg --import < $(public.secureFilePath)
- task: DownloadSecureFile@1
  name: secret
  displayName: 'Download Signing Secret Key'
  inputs:
    secureFile: 'secret.asc'
- script: |
    echo Installing $(secret.secureFilePath) to the keystore...
    sudo chown root:root $(secret.secureFilePath)
    sudo gpg --homedir /gpg --batch --import < $(secret.secureFilePath)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo chmod a+r /gpg/*
      echo Secret vars...
      echo gpg.keyname=$(gpg-keyname)
      echo gpg.passphrase=$(gpg-passphrase)
      echo sonatype-oss-password=$(sonatype-oss-password)
      echo sonatype-oss-username=$(sonatype-oss-username)
      echo Listing gpg public keys...
      sudo gpg -kv --homedir /gpg --keyid-format short
      echo Listing gpg secret keys...
      sudo gpg -Kv --homedir /gpg --keyid-format short
- task: Maven@3
  inputs:
    options: $(add-mvn-opts)
    mavenPomFile: 'extendedValidation-spring-boot-parent/pom.xml'
    mavenOptions: '-Xmx512m -DskipTests -Dmaven.javadoc.skip=true 
                   -Dgpg.passphrase=$(gpg-passphrase) 
                   -Dgpg.homedir=/gpg 
                   -Dsonatype-oss-password=$(sonatype-oss-password) 
                   -Dsonatype-oss-username=$(sonatype-oss-username)'
    goals: 'clean install'
- task: Maven@3
  inputs:
    options: $(add-mvn-opts)
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m -Dmaven.javadoc.skip=true -s maven/settings.xml
                   -Dgpg.passphrase=$(gpg-passphrase) 
                   -Dgpg.homedir=/gpg 
                   -Dsonatype-oss-password=$(sonatype-oss-password) 
                   -Dsonatype-oss-username=$(sonatype-oss-username)'
    publishJUnitResults: 'true'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package verify sonar:sonar deploy'
    