# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 18.04'
variables:
- group: krypto
steps:
- task: DownloadSecureFile@1
  name: keystore
  displayName: 'Download Signing Keystore'
  inputs:
    secureFile: 'keystore'
- script: |
    echo Installing $(keystore.secureFilePath) to the keystore...;
    sudo chown root:root $(keystore.secureFilePath);
    sudo chmod a+r $(keystore.secureFilePath);
    sudo ln -s $(keystore.secureFilePath) $(gpg-keyring);
- task: Bash@3
  inputs:
    targetType: 'inline'
- script: |
    echo Setting env vars...;
    export gpg-dir=$(krypto.gpg-dir);
    export gpg-keyname=$(krypto.gpg-keyname);
    export gpg-keyring=$(krypto.gpg-keyring);
    export gpg-passphrase=$(krypto.gpg-passphrase);
    export sonatype-oss-password=$(krypto.sonatype-oss-password);
    export sonatype-oss-username=$(krypto.sonatype-oss-username);
    echo gpg-dir=${krypto.gpg-dir};
    echo gpg-keyname=${krypto.gpg-keyname};
    echo gpg-keyring=${krypto.gpg-keyring};
    echo gpg-passphrase=${krypto.gpg-passphrase};
    echo sonatype-oss-password=${krypto.sonatype-oss-password};
    echo sonatype-oss-username=${krypto.sonatype-oss-username};
- task: Maven@3
  inputs:
    mavenPomFile: 'extendedValidation-spring-boot-parent/pom.xml'
    mavenOptions: '-Xmx1024m -DskipTests'
    goals: 'clean install'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'
    publishJUnitResults: 'true'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package verify sonar:sonar deploy'
