# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 18.04'
variables:
- group: krypto
steps:
- task: DownloadSecureFile@1
  name: keystore
  displayName: 'Download Signing Keystore'
  inputs:
    secureFile: 'keystore'
- script: |
    echo Installing $(keystore.secureFilePath) to the keystore...;
    sudo chown root:root $(keystore.secureFilePath);
    sudo chmod a+r $(keystore.secureFilePath);
    sudo ln -s $(keystore.secureFilePath) $(gpg-keyring);
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo Setting env vars...
      export GPG_DIR=$(gpg-dir)
      export GPG_KEYNAME=$(gpg-keyname)
      export GPG_KEYRING=$(gpg-keyring)
      export GPG_PASSPHRASE=$(gpg-passphrase)
      export SONATYPE_OSS_PASSWORD=$(sonatype-oss-password)
      export SONARYPE_OSS_USERNAME=$(sonatype-oss-username)
      echo gpg-dir=${GPG_DIR}
      echo gpg-keyname=${GPG_KEYNAME}
      echo gpg-keyring=${GPG_KEYRING}
      echo gpg-passphrase=${GPG_PASSPHRASE}
      echo sonatype-oss-password=${SONATYPE_OSS_PASSWORD}
      echo sonatype-oss-username=${SONARYPE_OSS_USERNAME}
- task: Maven@3
  inputs:
    mavenPomFile: 'extendedValidation-spring-boot-parent/pom.xml'
    mavenOptions: '-Xmx1024m -DskipTests -Dmaven.javadoc.skip=true'
    goals: 'clean install'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m -Dmaven.javadoc.skip=true -s maven/settings.xml'
    publishJUnitResults: 'true'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package verify sonar:sonar deploy'
