# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 18.04'
variables:
- group: krypto
steps:
- task: DownloadSecureFile@1
  name: keystore
  displayName: 'Download Signing Keystore'
  inputs:
    secureFile: 'keystore'
- script: |
  echo Installing $(keystore.secureFilePath) to the keystore...
  sudo chown root:root $(keystore.secureFilePath)
  sudo chmod a+r $(keystore.secureFilePath)
  sudo mkdir ~/.gpg
  sudo ln -s -t ~/.gpg/keystore $(keystore.secureFilePath)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'
    publishJUnitResults: 'true'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package verify sonar:sonar deploy'
